"""initial_schema_m1

Revision ID: a6dacb25e406
Revises: 
Create Date: 2026-09-19 22:48:49.250389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6dacb25e406'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'geom',
               existing_type=sa.NUMERIC(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'geom',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
