"""API routes. All 15 /api paths preserved.

M0 changes:
  - /api/locations no longer serves random.uniform hazard values (defect 5).
    Geographic identity is kept; hazard attributes are withheld with
    provenance = UNVERIFIED_SEED.
  - /api/risk/{id} no longer feeds the model an implicit 0 mm of rainfall,
    which systematically under-stated risk. It joins observed weather, or
    returns NO DATA.
  - /api/location/{id}, /api/satellite/{id} and /api/export/report/{id} no
    longer call the fabricated satellite index function (defect 1).
  - POST /api/alerts is closed pending auth in M11 (defect 7).
  - Every hazard-bearing response carries the advisory notice naming IMD,
    NDMA and NCS.
"""
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, Depends, HTTPException
from sqlalchemy.orm import Session

from backend.app.core.config import ADVISORY_NOTICE, settings
from backend.app.core.database import get_db
from backend.app.core.freshness import no_data, utcnow
from backend.app.core.mode import DEMO_LABEL, is_demo
from backend.app.ingestion.rate_limiter import get_rate_limiter
from backend.app.ingestion.registry import source_registry
from backend.app.ingestion.scheduler import ingestion_scheduler
from backend.app.models.db_models import DataSource, SourceHealth
from backend.app.models.schema import (
    LocationResponse, PredictRequest, PredictResponse,
    SimulationRequest, SimulationResponse,
    SatelliteInfoResponse, StateDistrictHierarchyItem,
)
from backend.app.services.alert_service import (
    WRITE_DISABLED_REASON, evaluate_threshold_breach, get_recent_alerts,
)
from backend.app.services.ml_service import get_model_info, predict_risk, simulate_scenario
from backend.app.services.satellite_service import get_available_layers, get_satellite_observation
from backend.app.services.weather_service import fetch_live_weather

router = APIRouter()

DATA_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "ne_india_locations.json"
LGD_DATA_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "lgd_administrative_units.json"
GEO_DATA_PATH = Path(__file__).resolve().parent.parent.parent.parent / "frontend" / "data" / "geo_data.json"
LOCATIONS_CACHE: List[Dict[str, Any]] = []

# Fields produced by random.uniform / random.randint in seed_locations.py.
# Stripped on load so they cannot reach a response or a model input.
FABRICATED_FIELDS = (
    "risk_probability", "risk_category", "flood_risk_category",
    "key_risk_factors", "snow_cover_pct", "snowmelt_rate", "bare_soil_pct",
    "vegetation_index", "farm_change_flag", "flood_extent_flag",
    "historical_landslides", "distance_road", "distance_river", "aspect",
    "land_cover", "satellite_source", "is_sample_data",
)


def _classify_provenance(record: dict) -> str:
    """Curated sites were hand-entered; 'Sector-N' sites were generated by
    jittering a random parent's coordinates."""
    return "SYNTHETIC_SEED" if "Sector-" in record.get("name", "") else "CURATED_SEED"


def get_all_cached_locations() -> List[Dict[str, Any]]:
    global LOCATIONS_CACHE
    if not LOCATIONS_CACHE:
        cleaned = []
        seen_districts = set()

        # 1. Load field monitoring locations from ne_india_locations.json
        if DATA_PATH.exists():
            with open(DATA_PATH, "r", encoding="utf-8") as f:
                raw = json.load(f)
            for rec in raw:
                item = {k: v for k, v in rec.items() if k not in FABRICATED_FIELDS}
                item["provenance"] = _classify_provenance(rec)
                item["data_status"] = "NO_DATA"
                cleaned.append(item)
                key = (item.get("state", "").lower(), item.get("district", "").lower())
                seen_districts.add(key)

        # 2. Fold in all 788 authoritative LGD districts for complete All-India coverage
        source_path = LGD_DATA_PATH if LGD_DATA_PATH.exists() else GEO_DATA_PATH
        if source_path.exists():
            with open(source_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            districts = data.get("districts", [])
            current_id = max((l["id"] for l in cleaned), default=0) + 1
            for d in districts:
                st = d.get("state") or d.get("s", "Unknown")
                dist_name = d.get("name") or d.get("n", "Unknown")
                key = (st.lower(), dist_name.lower())
                if key not in seen_districts:
                    lat = float(d["latitude"]) if "latitude" in d else (float(d["ll"][0]) if d.get("ll") else 20.0)
                    lon = float(d["longitude"]) if "longitude" in d else (float(d["ll"][1]) if d.get("ll") else 78.0)
                    tier = d.get("tier", 1)
                    elev = float(d.get("elevation_m") if d.get("elevation_m") is not None else d.get("e", 500))
                    slope = float(d.get("slope_deg") if d.get("slope_deg") is not None else d.get("sl", 15.0))
                    geom_status = d.get("geometry_status") or d.get("status", "AVAILABLE")
                    item = {
                        "id": current_id,
                        "name": dist_name,
                        "district": dist_name,
                        "state": st,
                        "lgd_code": d.get("lgd_code"),
                        "lgd_state_code": d.get("lgd_state_code"),
                        "latitude": lat,
                        "longitude": lon,
                        "elevation": elev,
                        "slope": slope,
                        "soil_type": d.get("soil", "Clay Loam"),
                        "geology": d.get("geo", "Sedimentary"),
                        "coverage_tier": "FULL_HAZARD_MONITORING" if tier == 1 else "SCREENING" if tier == 2 else "PLAINS",
                        "has_prediction": tier == 1,
                        "geometry_status": geom_status,
                        "terrain_provenance": "ESTIMATED / HEURISTIC — pending Copernicus GLO-30 DEM ingestion (see ARCHITECTURE.md)",
                        "provenance": "CURATED_SEED",
                        "data_status": "NO_DATA"
                    }
                    cleaned.append(item)
                    seen_districts.add(key)
                    current_id += 1

        LOCATIONS_CACHE = cleaned
    return LOCATIONS_CACHE


def _find(loc_id: int) -> Dict[str, Any]:
    loc = next((l for l in get_all_cached_locations() if l["id"] == loc_id), None)
    if not loc:
        raise HTTPException(status_code=404, detail=f"Location ID {loc_id} not found.")
    return loc


def _envelope(payload: dict) -> dict:
    payload["advisory"] = ADVISORY_NOTICE
    payload["timestamp"] = utcnow().isoformat()
    if is_demo():
        payload["data_mode"] = DEMO_LABEL
    return payload


def _features_from(loc: dict, weather: dict, satellite: dict) -> Optional[dict]:
    """Assemble a model input vector from OBSERVED values only.

    Returns None when a required observation is missing, so the caller can
    return NO DATA instead of a score computed from absent rainfall.
    """
    observed = (weather or {}).get("observed") or {}
    if observed.get("rainfall_24h") is None:
        return None
    features = dict(loc)
    features.update({
        "rainfall_1h": observed.get("rainfall_1h") or 0.0,
        "rainfall_24h": observed.get("rainfall_24h"),
        "rainfall_7d_cumulative": observed.get("rainfall_7d_cumulative") or 0.0,
        "rainfall_intensity": observed.get("rainfall_1h") or 0.0,
    })
    for key in ("snow_cover_pct", "snowmelt_rate", "bare_soil_pct", "vegetation_index"):
        value = (satellite or {}).get(key)
        if value is not None:
            features[key] = value
    return features


def _unavailable_prediction(weather: dict, satellite: dict) -> dict:
    return {
        "hazard_index": None,
        "risk_category": None,
        "flood_index": None,
        "flood_risk_category": None,
        "key_risk_factors": None,
        "top_factors": {},
        "shap_values": {},
        "status": "NO_DATA",
        "reason": "No observed rainfall available; a hazard index is not computed "
                  "from absent inputs.",
        "inputs": {
            "weather": (weather or {}).get("data_status"),
            "satellite": (satellite or {}).get("data_status"),
        },
    }


@router.get("/locations", response_model=List[LocationResponse])
async def get_locations(state: Optional[str] = None, district: Optional[str] = None,
                        risk: Optional[str] = None):
    """Monitoring sites. Hazard attributes are withheld pending M1."""
    locs = get_all_cached_locations()
    if state:
        locs = [l for l in locs if l.get("state", "").lower() == state.lower()]
    if district:
        locs = [l for l in locs if l.get("district", "").lower() == district.lower()]
    if risk:
        # Risk filtering needs a real risk value. None exists yet.
        locs = []
    return locs


@router.get("/hierarchy", response_model=List[StateDistrictHierarchyItem])
async def get_state_district_hierarchy():
    state_map: Dict[str, Dict[str, Any]] = {}
    for loc in get_all_cached_locations():
        st = loc.get("state", "Unknown")
        dist = loc.get("district", st)
        entry = state_map.setdefault(st, {
            "districts": set(), "total_locations": 0, "hazard_monitoring_active": False,
        })
        entry["districts"].add(dist)
        entry["total_locations"] += 1
        # No location has active hazard monitoring until ingestion lands (M3/M4).
    return [
        StateDistrictHierarchyItem(
            state=st, districts=sorted(d["districts"]),
            total_locations=d["total_locations"],
            hazard_monitoring_active=d["hazard_monitoring_active"],
        )
        for st, d in sorted(state_map.items())
    ]


@router.get("/location/{loc_id}")
async def get_location_detail(loc_id: int):
    loc = _find(loc_id)
    weather = await fetch_live_weather(loc["latitude"], loc["longitude"])
    satellite = get_satellite_observation(loc)

    features = _features_from(loc, weather, satellite)
    prediction = predict_risk(features) if features else _unavailable_prediction(weather, satellite)

    return _envelope({
        "location": loc,
        "weather": weather,
        "satellite": satellite,
        "prediction": prediction,
        "threshold_alert": evaluate_threshold_breach(loc, weather, prediction),
        "disclaimer": settings.PROTOTYPE_DISCLAIMER,
    })


@router.get("/weather/district/{district_id}")
async def get_district_weather(district_id: int, db: Session = Depends(get_db)):
    """Retrieve reconciled weather and Antecedent Saturation Index (ASI) for a district."""
    from backend.app.services.weather_reconciliation import WeatherReconciliationService
    reconciled = WeatherReconciliationService.get_reconciled_district_weather(district_id, db)
    return _envelope(reconciled)


@router.get("/weather/asi/{district_id}")
async def get_district_asi(district_id: int, db: Session = Depends(get_db)):
    """Retrieve 10-day Antecedent Saturation Index (ASI) calculated from observed rainfall."""
    from backend.app.services.weather_reconciliation import WeatherReconciliationService
    asi_val = WeatherReconciliationService.compute_district_asi(district_id, db)
    return _envelope({
        "district_id": district_id,
        "antecedent_saturation_index": asi_val,
        "decay_factor": 0.85,
        "window_days": 10,
    })


@router.get("/weather/{lat}/{lon}")
async def get_weather(lat: float, lon: float):
    return await fetch_live_weather(lat, lon)


@router.post("/predict", response_model=PredictResponse)
async def predict_custom_landslide(payload: PredictRequest):
    result = predict_risk(payload.model_dump())
    return PredictResponse(
        hazard_index=result["hazard_index"],
        risk_category=result["risk_category"],
        flood_index=result["flood_index"],
        flood_risk_category=result["flood_risk_category"],
        top_factors=result["top_factors"],
        shap_values=result["shap_values"],
        disclaimer=settings.PROTOTYPE_DISCLAIMER,
        timestamp=utcnow().isoformat(),
    )


@router.post("/predict/flood")
async def predict_custom_flood(payload: PredictRequest):
    result = predict_risk(payload.model_dump())
    return _envelope({
        "flood_index": result["flood_index"],
        "flood_risk_category": result["flood_risk_category"],
        "calibration": result["calibration"],
        "index_note": result["index_note"],
        "disclaimer": settings.PROTOTYPE_DISCLAIMER,
    })


@router.get("/risk/{loc_id}")
async def get_location_risk(loc_id: int):
    """Joins observed weather before scoring.

    The baseline passed the bare location record to the model, so rainfall
    defaulted to 0.0 mm and the endpoint reported Low risk during rainfall it
    had simply never been given.
    """
    loc = _find(loc_id)
    weather = await fetch_live_weather(loc["latitude"], loc["longitude"])
    satellite = get_satellite_observation(loc)
    features = _features_from(loc, weather, satellite)

    if features is None:
        return _envelope({
            "location_id": loc_id, "name": loc["name"], "state": loc["state"],
            "district": loc.get("district", loc["state"]),
            **_unavailable_prediction(weather, satellite),
            "disclaimer": settings.PROTOTYPE_DISCLAIMER,
        })

    res = predict_risk(features)
    return _envelope({
        "location_id": loc_id, "name": loc["name"], "state": loc["state"],
        "district": loc.get("district", loc["state"]),
        "hazard_index": res["hazard_index"],
        "risk_category": res["risk_category"],
        "calibration": res["calibration"],
        "index_note": res["index_note"],
        "key_risk_factors": res["key_risk_factors"],
        "top_factors": res["top_factors"],
        "inputs": {"weather": weather.get("data_status"),
                   "satellite": satellite.get("data_status")},
        "disclaimer": settings.PROTOTYPE_DISCLAIMER,
    })


@router.get("/satellite/{loc_id}", response_model=SatelliteInfoResponse)
async def get_satellite_info(loc_id: int):
    loc = _find(loc_id)
    sat = get_satellite_observation(loc)
    return SatelliteInfoResponse(
        location_id=loc_id, location_name=loc["name"],
        district=loc.get("district", loc["state"]), state=loc.get("state"),
        snow_cover_pct=sat.get("snow_cover_pct"),
        snowmelt_rate=sat.get("snowmelt_rate"),
        bare_soil_pct=sat.get("bare_soil_pct"),
        vegetation_index=sat.get("vegetation_index"),
        farm_change_flag=sat.get("farm_change_flag"),
        flood_extent_flag=sat.get("flood_extent_flag"),
        source=sat.get("source"),
        last_updated=sat.get("last_updated"),
        disclaimer=ADVISORY_NOTICE,
    )


@router.get("/satellite/layers/info")
async def get_satellite_layer_metadata():
    return get_available_layers()


@router.get("/alerts")
async def list_alerts(limit: int = 10):
    return get_recent_alerts(limit)


@router.post("/alerts", status_code=503)
async def create_new_alert(
    location_id: int = Body(...), location_name: str = Body(...),
    state: str = Body(...), hazard_type: str = Body("Landslide"),
    severity: str = Body("High"), title: str = Body(...), message: str = Body(...),
):
    """Closed in M0. The baseline accepted unauthenticated writes (defect 7)."""
    raise HTTPException(status_code=503, detail=WRITE_DISABLED_REASON)


@router.get("/history/{loc_id}")
async def get_history(loc_id: int):
    loc = _find(loc_id)
    weather = await fetch_live_weather(loc["latitude"], loc["longitude"])
    return _envelope({
        "location_id": loc_id, "name": loc["name"],
        "rainfall_trend_7d": weather.get("rainfall_trend_7d", []),
        "data_status": weather.get("data_status"),
        "disclaimer": settings.PROTOTYPE_DISCLAIMER,
    })


@router.post("/simulation", response_model=SimulationResponse)
async def run_simulation(payload: SimulationRequest):
    """What-if scenario. Explicitly hypothetical, so it may run on stated
    inputs — but it must not silently borrow absent observations."""
    locs = get_all_cached_locations()
    if not locs:
        raise HTTPException(status_code=404, detail="No locations available.")
    loc = next((l for l in locs if l["id"] == (payload.location_id or 1)), locs[0])

    weather = await fetch_live_weather(loc["latitude"], loc["longitude"])
    observed = (weather or {}).get("observed") or {}
    base = dict(loc)
    base.update({
        "rainfall_1h": observed.get("rainfall_1h") or 0.0,
        "rainfall_24h": observed.get("rainfall_24h") or 0.0,
        "rainfall_7d_cumulative": observed.get("rainfall_7d_cumulative") or 0.0,
        "rainfall_intensity": observed.get("rainfall_1h") or 0.0,
    })
    sim = simulate_scenario(base, payload.model_dump())
    return SimulationResponse(
        original_hazard_index=sim["original_hazard_index"],
        simulated_hazard_index=sim["simulated_hazard_index"],
        original_risk_category=sim["original_risk_category"],
        simulated_risk_category=sim["simulated_risk_category"],
        delta_index=sim["delta_index"],
        simulated_flood_index=sim["simulated_flood_index"],
        simulated_flood_category=sim["simulated_flood_category"],
        factor_changes=sim["factor_changes"],
        disclaimer=settings.PROTOTYPE_DISCLAIMER,
    )


@router.get("/model/info")
async def get_ml_model_info():
    return get_model_info()


@router.get("/export/report/{loc_id}")
async def export_risk_report(loc_id: int):
    loc = _find(loc_id)
    weather = await fetch_live_weather(loc["latitude"], loc["longitude"])
    satellite = get_satellite_observation(loc)
    features = _features_from(loc, weather, satellite)
    hazard = predict_risk(features) if features else _unavailable_prediction(weather, satellite)

    return _envelope({
        "title": f"LANDSAFE-NER Hazard Assessment — {loc['name']}, "
                 f"{loc.get('district', '')}, {loc['state']}",
        "generated_at": utcnow().isoformat(),
        "advisory_notice": ADVISORY_NOTICE,
        "location_metadata": loc,
        "sources": {
            "weather": weather.get("data_status"),
            "satellite": satellite.get("data_status"),
            "model": get_model_info().get("calibration"),
        },
        "observed_weather": weather.get("observed"),
        "forecast": weather.get("forecast"),
        "satellite_observations": {
            k: satellite.get(k) for k in
            ("snow_cover_pct", "snowmelt_rate", "bare_soil_pct",
             "vegetation_index", "farm_change_flag", "flood_extent_flag")
        },
        "hazard_assessment": {
            "hazard_index": hazard.get("hazard_index"),
            "risk_category": hazard.get("risk_category"),
            "flood_index": hazard.get("flood_index"),
            "calibration": hazard.get("calibration", "UNCALIBRATED"),
            "note": hazard.get("index_note") or hazard.get("reason"),
            "attribution": hazard.get("top_factors", {}),
        },
    })


@router.get("/sources")
async def list_data_sources(db: Session = Depends(get_db)):
    """List all registered data sources with current health and verification state."""
    sources_in_db = db.query(DataSource).all()
    results = []
    for src in sources_in_db:
        health = src.health
        rate_limiter = get_rate_limiter(src.id)
        is_verified = source_registry.is_verified(src.id)
        results.append({
            "id": src.id,
            "name": src.name,
            "provider": src.provider,
            "cadence_minutes": src.cadence_minutes,
            "licence": src.licence,
            "api_endpoint": src.api_endpoint,
            "is_active": src.is_active,
            "is_verified": is_verified,
            "health": {
                "status": health.status if health else "UNKNOWN",
                "last_successful_fetch": health.last_successful_fetch.isoformat() if health and health.last_successful_fetch else None,
                "last_attempt_status": health.last_attempt_status if health else None,
                "consecutive_failures": health.consecutive_failures if health else 0,
                "average_latency_ms": health.average_latency_ms if health else 0.0,
                "updated_at": health.updated_at.isoformat() if health and health.updated_at else None,
            },
            "rate_limit": rate_limiter.get_status()
        })
    return _envelope({
        "total_sources": len(results),
        "sources": results
    })


@router.get("/sources/{source_id}/health")
async def get_source_health(source_id: str, db: Session = Depends(get_db)):
    """Get detailed health and quota status for a single source."""
    src = db.query(DataSource).filter(DataSource.id.ilike(source_id)).first()
    if not src:
        raise HTTPException(status_code=404, detail=f"Source '{source_id}' not found.")

    health = src.health
    rate_limiter = get_rate_limiter(src.id)
    is_verified = source_registry.is_verified(src.id)
    return _envelope({
        "id": src.id,
        "name": src.name,
        "provider": src.provider,
        "cadence_minutes": src.cadence_minutes,
        "licence": src.licence,
        "is_active": src.is_active,
        "is_verified": is_verified,
        "health": {
            "status": health.status if health else "UNKNOWN",
            "last_successful_fetch": health.last_successful_fetch.isoformat() if health and health.last_successful_fetch else None,
            "last_attempt_status": health.last_attempt_status if health else None,
            "consecutive_failures": health.consecutive_failures if health else 0,
            "average_latency_ms": health.average_latency_ms if health else 0.0,
            "updated_at": health.updated_at.isoformat() if health and health.updated_at else None,
        },
        "rate_limit": rate_limiter.get_status()
    })


@router.post("/sources/{source_id}/trigger")
async def trigger_source_ingestion(source_id: str):
    """Trigger manual on-demand ingestion cycle for a source."""
    try:
        result = await ingestion_scheduler.trigger_now(source_id)
        return _envelope(result)
    except ValueError as ex:
        raise HTTPException(status_code=404, detail=str(ex))
    except Exception as ex:
        raise HTTPException(status_code=500, detail=str(ex))

